language: python
cache: pip
dist: xenial

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py27-dj111
      python: 2.7
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=py36-dj21
      python: 3.6
    - env: TOXENV=py37-dj21
      python: 3.7
    - env: TOXENV=py37-dj22
      python: 3.7
    - env: TOXENV=docs
      python: 3.6

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
